spring.application.name=e-commerceJumbotail 

server.port=5000

spring.datasource.url=jdbc:postgresql://localhost:5432/Jumbotail e-commerce
spring.datasource.username=postgres
spring.datasource.password=vishu$2006
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=ad5b0f184d7a538cc67343733a1203f2bad33fd6004ac3a8cdf83ba681228b2ffb71af76c1b6a1b2a043cedb59bd65847c2de680a97b64d349bc3d580c42ac70
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web.servlet=TRACE