spring.application.name=e-commerceJumbotail 

server.port=5000

spring.datasource.url=jdbc:postgresql://localhost:5432/Jumbotail e-commerce
spring.datasource.username=postgres
spring.datasource.password=vishu$2006
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true